# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Hollows_Engine_config = debug
  Assets_config = debug

else ifeq ($(config),release)
  Hollows_Engine_config = release
  Assets_config = release

else ifeq ($(config),dist)
  Hollows_Engine_config = dist
  Assets_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Hollows_Engine Assets

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Hollows_Engine:
ifneq (,$(Hollows_Engine_config))
	@echo "==== Building Hollows_Engine ($(Hollows_Engine_config)) ===="
	@${MAKE} --no-print-directory -C src/engine -f Makefile config=$(Hollows_Engine_config)
endif

Assets: Hollows_Engine
ifneq (,$(Assets_config))
	@echo "==== Building Assets ($(Assets_config)) ===="
	@${MAKE} --no-print-directory -C src/assets -f Makefile config=$(Assets_config)
endif

clean:
	@${MAKE} --no-print-directory -C src/engine -f Makefile clean
	@${MAKE} --no-print-directory -C src/assets -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Hollows_Engine"
	@echo "   Assets"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"